export const DEFAULT_GRIEVANCE_REPORT = {
  monthEnding: 'June 2026',
  impersonationComplaints: '0',
  summaryRows: [
    {
      srNo: '1',
      source: 'Directly from Investors',
      pendingLastMonth: '0',
      received: '0',
      resolved: '0',
      totalPending: '0',
      pendingOver3Months: '0',
      avgResolutionDays: '0',
    },
    {
      srNo: '2',
      source: 'SEBI (SCORES)',
      pendingLastMonth: '0',
      received: '0',
      resolved: '0',
      totalPending: '0',
      pendingOver3Months: '0',
      avgResolutionDays: '0',
    },
    {
      srNo: '3',
      source: 'Other Sources (if any)',
      pendingLastMonth: '0',
      received: '0',
      resolved: '0',
      totalPending: '0',
      pendingOver3Months: '0',
      avgResolutionDays: '0',
    },
    {
      srNo: '4',
      source: 'Grand Total',
      pendingLastMonth: '0',
      received: '0',
      resolved: '0',
      totalPending: '0',
      pendingOver3Months: '0',
      avgResolutionDays: '0',
    },
  ],
  monthlyTrend: [
    { srNo: '1', month: 'April 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '2', month: 'May 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '3', month: 'June 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '4', month: 'July 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '5', month: 'August 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '6', month: 'September 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '7', month: 'October 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '8', month: 'November 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '9', month: 'December 2024', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '10', month: 'January 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '11', month: 'February 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '12', month: 'March 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '13', month: 'April 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '14', month: 'May 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '15', month: 'June 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '16', month: 'July 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '17', month: 'Aug 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '18', month: 'Sep 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '19', month: 'Oct 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '20', month: 'Nov 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '21', month: 'Dec 2025', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '22', month: 'Jan 2026', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '23', month: 'Feb 2026', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '24', month: 'Mar 2026', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '25', month: 'Apr 2026', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '26', month: 'May 2026', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '27', month: 'June 2026', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
  ],
  annualTrend: [
    { srNo: '1', year: '2024-25', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
    { srNo: '2', year: '2025-26', carriedForward: '0', received: '0', resolved: '0', pending: '0' },
  ],
};

export function cloneDefaultGrievanceReport() {
  return JSON.parse(JSON.stringify(DEFAULT_GRIEVANCE_REPORT));
}
